INSERT INTO USERMANAGER.USERS (ID, USER_FULL_NAME) VALUES ('1', 'First User');
  INSERT INTO USERMANAGER.USERS (ID, USER_FULL_NAME) VALUES ('2', 'Second User');
  INSERT INTO USERMANAGER.USERS (ID, USER_FULL_NAME) VALUES ('3', 'Third User');
  INSERT INTO USERMANAGER.USERS (ID, USER_FULL_NAME) VALUES ('4', 'Fourth User');
  INSERT INTO usermanager.users (ID, USER_FULL_NAME) VALUES ('5', 'Fifth User');
  INSERT INTO USERMANAGER.USERS (ID, USER_FULL_NAME) VALUES ('6', 'Sixth User');
